name: joplin-desktop
base: core20
summary: A free, private note taking and to-do app!
description: |
  Joplin is an open source, free note taking application. Designed to be capable of replacing Evernote, Joplin is privacy conscious and can be be used without signing up for an account, but optionally supports synchronising your files with a file host of your choice and with optional end to end encryption.
  
  Developer site: https://joplinapp.org/
  
  Snap build: https://github.com/MrCarroll/joplin-snap
grade: stable
confinement: strict
license: MIT
adopt-info: joplin
compression: lzo

package-repositories:
  - type: apt
    url: https://deb.nodesource.com/node_16.x
    components: [main]
    suites: [focal]
    key-id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280

parts:
  joplin:
    plugin: joplin
    source: https://github.com/laurent22/joplin.git
    source-commit: 105a61c1eec1fd307698c4bfdd490f0d4a26852e # 2.7.11
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
      - libglu1-mesa
      - libnotify4
      - libnotify-bin
      - libpulse0
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags)

  xdg-open:
    plugin: go
    source-type: local
    source: ./xdg-open
    organize:
      bin/dbus: bin/xdg-open

  cleanup:
    plugin: nil
    build-snaps:
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [joplin, xdg-open]


layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

apps:
  joplin-desktop:
    command: opt/joplin-desktop/joplin --no-sandbox
    plugs:
      - network
      - browser-support
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - home
      - removable-media
      - password-manager-service
      - audio-playback
      - cups-control
      - avahi-control
    extensions: [gnome-3-38]
    environment:
      TMPDIR: ${XDG_RUNTIME_DIR}
      PATH: ${SNAP}/bin:${PATH}
