name: joplin-james-carroll
base: core18
summary: A free, private note taking and to-do app!
description: |
  Joplin is an open source, free note taking application. Designed to be capable of replacing Evernote, Joplin is privacy conscious and can be be used without signing up for an account, but optionally supports synchronising your files with a file host of your choice and with optional end to end encryption.
  
  Developer site: https://joplinapp.org/
  
  Snap build: https://github.com/MrCarroll/joplin-snap
grade: stable
confinement: strict
license: MIT
adopt-info: joplin
architectures:
  - build-on: amd64

parts:
  joplin:
    plugin: nodejs
    nodejs-version: '14.15.1'
    nodejs-package-manager: 'npm'
    source: https://github.com/laurent22/joplin.git
    source-tag: 'v1.4.12'
    source-depth: 1
    build-environment:
      - npm_config_unsafe_perm: 'true'
      - SUDO_UID: '0'
      - SUDO_GID: '0'
      - SUDO_USER: 'root'
      - npm_config_prefer_offline: 'true'
    build-packages:
      - python
      - rsync
      - libsecret-1-dev
      - curl
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
      sed -i '/function checkForUpdates/a return;' packages/app-desktop/checkForUpdates.js
    override-build: |
      export PATH=${SNAPCRAFT_PART_BUILD}/../npm/bin:${PATH}
      npm install
      cd packages/app-desktop
      npm run dist
      cp -r dist/linux-unpacked ${SNAPCRAFT_PART_INSTALL}
      mv ${SNAPCRAFT_PART_INSTALL}/linux-unpacked/@joplinapp-desktop ${SNAPCRAFT_PART_INSTALL}/linux-unpacked/joplin
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
      - libglu1-mesa
      - libnotify4
      - libpulse0
      - libappindicator3-1

apps:
  joplin:
    command: linux-unpacked/joplin --no-sandbox
    plugs:
      - network
      - browser-support
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - home
      - removable-media
      - password-manager-service
      - pulseaudio
      - audio-playback
    extensions: [gnome-3-28]
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: ${XDG_RUNTIME_DIR}
