name: joplin-desktop
base: core20
summary: A free, private note taking and to-do app!
description: |
  Joplin is an open source, free note taking application. Designed to be capable of replacing Evernote, Joplin is privacy conscious and can be be used without signing up for an account, but optionally supports synchronising your files with a file host of your choice and with optional end to end encryption.
  
  Developer site: https://joplinapp.org/
  
  Snap build: https://github.com/MrCarroll/joplin-snap
grade: stable
confinement: strict
license: MIT
adopt-info: joplin
compression: lzo

parts:
  joplin:
    plugin: joplin
    source: https://github.com/laurent22/joplin.git
    source-tag: 'v2.4.9'
    source-depth: 1
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
      - libglu1-mesa
      - libnotify4
      - libnotify-bin
      - libpulse0
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags)
  xdg-open:
    plugin: go
    source-type: local
    source: ./xdg-open
    organize:
      bin/dbus: opt/joplin-open/open
  cleanup:
    plugin: nil
    build-snaps:
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [joplin, xdg-open]


layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/bin/joplin-open:
    symlink: $SNAP/opt/joplin-open/open

apps:
  joplin-desktop:
    command: opt/joplin-desktop/joplin --no-sandbox
    plugs:
      - network
      - browser-support
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - home
      - removable-media
      - password-manager-service
      - audio-playback
      - cups-control
      - avahi-control
    extensions: [gnome-3-38]
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: ${XDG_RUNTIME_DIR}
