name: Basic build test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v4
      with:
        name: '${{ github.sha }}.snap'
        path: ${{ steps.build.outputs.snap}}
