name: Automatically check for upstream releases
on:
  schedule:
   - cron: "0 20 * * *"
jobs:
  Update-Tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{ secrets.MRCARROLLTOKEN }}
    - name: Check for and apply latest stable tag
      run: |
        curTag=$(awk '/source-tag/ {print $2}' snap/snapcraft.yaml)
        latestTag=$(curl https://api.github.com/repos/laurent22/joplin/releases/latest | jq -r '.tag_name')
        echo $curTag vs $latestTag
        if [[ "${curTag:1:-1}" == "$latestTag" ]]
        then
          echo "The latest stable release and the source-tag property are aligned. There's nothing to do."
        else
          echo "The latest stable release and the source tag aren't aligned. Triggering a rebuild."
          sed -i "s/$curTag/'$latestTag'/1" snap/snapcraft.yaml
          git add snap/snapcraft.yaml
          git config user.name "James Carroll"
          git config user.email "eloquism@gmail.com"
          git commit -m "auto: Update to $latestTag"
          git push
        fi

